# -*- coding: utf-8 -*-
"""Neural Network .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CihFnt75t8ek1wr1o0JZUH1qfSLCf8ec
"""

import numpy as np
import matplotlib.pyplot as plt

# input data
inputs = np.array([[0, 1, 0],
                   [0, 1, 1],
                   [0, 0, 0],
                   [1, 0, 0],
                   [1, 1, 1],
                   [1, 0, 1]])
# output data
outputs = np.array([[0], [0], [0], [1], [1], [1]])

class NeuralNetwork:
    def __init__(self, inputs, outputs, learning_rate=0.1, momentum=0.9):
        self.inputs = inputs
        self.outputs = outputs
        self.weights = np.random.rand(inputs.shape[1], 1)
        self.learning_rate = learning_rate
        self.momentum = momentum
        self.error_history = []
        self.epoch_list = []
        self.weight_history = []

    def sigmoid(self, x, deriv=False):
        if deriv:
            return x * (1 - x)
        return 1 / (1 + np.exp(-x))

    def feed_forward(self):
        self.hidden = self.sigmoid(np.dot(self.inputs, self.weights))

    def backpropagation(self):
        error = self.outputs - self.hidden
        delta = error * self.sigmoid(self.hidden, deriv=True)
        weight_update = np.dot(self.inputs.T, delta) * self.learning_rate
        self.weights += weight_update + (self.momentum * weight_update)
        self.weight_history.append(np.mean(self.weights))

    def train(self, epochs=25000):
        for epoch in range(epochs):
            self.feed_forward()
            self.backpropagation()
            # Record the error
            self.error_history.append(np.average(np.abs(self.outputs - self.hidden)))
            self.epoch_list.append(epoch)

    def predict(self, new_input):
        return self.sigmoid(np.dot(new_input, self.weights))

# create neural network
NN = NeuralNetwork(inputs, outputs)
# train neural network
NN.train()

# create two new examples to predict
example = np.array([[1, 1, 0]])
example_2 = np.array([[0, 1, 1]])

# print the predictions for both examples
print(NN.predict(example), ' - Correct: ', example[0][0])
print(NN.predict(example_2), ' - Correct: ', example_2[0][0])

# plot the error over the entire training duration
plt.figure(figsize=(15,5))
plt.plot(NN.epoch_list, NN.error_history)
plt.xlabel('Epoch')
plt.ylabel('Error')
plt.show()